config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "products#index"
  resources :products, only: [:index, :show]

  # backend
  namespace :admin do 
    root "products#index"
    resources :products do 
      delete :remove_image, on: :member
    end 
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :status, presence: true 
  validates :list_price, :sell_price, :SKU, numericality: { greater_than: 0 }

  has_many_attached :images
  
  enum status: { unreleased: 0, processing: 1, released: 2}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :find_product, except: [:index, :new, :create]
  before_action :authenticate_user!

  def index
    @products = Product.all
  end 

  def show
  end 

  def new 
    @product = Product.new 
  end 

  def create 
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path, notice: 'Product is created.'
    else 
      render :new 
    end 
  end 

  def edit 
  end 

  def update
    # p "="*50
    # p "#{update_params}"
    # p "="*50 
    # p "#{params[:product][:images]}"
    # p "="*50 
    if @product.update(update_params)
      if params[:product][:images].present?
        @product.images.attach(params[:product][:images])
      end
      redirect_to admin_products_path 
    else 
      render :edit 
    end 
  end 

  def destroy 
    @product.destroy 
    redirect_to admin_products_path, notice: 'Product is removed.'
  end 

  def remove_image 
    @product.images.find(params[:format]).purge
    render :edit
  end

  private 
  def product_params
    params.require(:product).permit(:name, 
                                    :status, 
                                    :description, 
                                    :list_price,
                                    :sell_price,
                                    :SKU,
                                    images:[])
  end 

  def update_params
    params.require(:product).permit(:name, 
                                    :status, 
                                    :description, 
                                    :list_price,
                                    :sell_price,
                                    :SKU)
  end 

  def find_product 
    @product = Product.find(params[:id])
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController 
  before_action :find_product, only: [:show]

  layout 'frontend'

  def index
    @products = Product.released
                       .with_attached_images
  end 

  def show
  end 

  private
  def find_product 
    @product = Product.find(params[:id])
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/products/_form.html.erb
<% if product.errors.any? %>
<ul>
  <% product.errors.full_messages.each do |message| %>
  <li class="has-text-danger"><%= message %></li>
  <% end %>
</ul>
<% end %>

<!-- form -->
<%= form_for ([:admin, product]) do |f| %>
<div class="columns">
  <div class="column is-5">
    <div class="field">
      <%= f.label :name, class:'label' %>
      <div class="control">
        <%= f.text_field :name, class:'input' %>
      </div>
    </div>
  </div>

  <div class="column is-3">
    <div class="field">
      <%= f.label :status, class:'label' %>
      <div class="select">
        <%= f.select :status, Product.statuses.keys %>
      </div>
    </div>
  </div>
</div>

<div class="columns">
  <div class="column is-5">
    <div class="field">
      <%= f.label :description, class:'label' %>
      <div class="control">
        <%= f.text_area :description, class:'input' %>
      </div>
    </div>
  </div>
</div>
<div class="columns">
  <div class="column">
    <div class="field">
      <%= f.label :images, class:'label' %>
      <%= f.file_field :images, multiple: true %>
    </div>
  </div>
</div>

<div class="columns">
  <div class="column is-2">
    <div class="field">
      <%= f.label :list_price, class:'label' %>
      <div class="control">
        <%= f.number_field :list_price, class:'input' %>
      </div>
    </div>
  </div>

  <div class="column is-2">
    <div class="field">
      <%= f.label :sell_price, class:'label' %>
      <div class="control">
        <%= f.number_field :sell_price, class:'input' %>
      </div>
    </div>
  </div>
  <div class="column is-2">
    <div class="field">
      <%= f.label :SKU, class:'label' %>
      <div class="control">
        <%= f.number_field :SKU, class:'input' %>
      </div>
    </div>
  </div>
</div>

<div class="coulmns">
  <div class="coulmn is-2">
    <div class="field is-grouped">
      <div class="control">
        <%= f.submit class:'button is-primary' %>
      </div>
      <div class="control">
        <%= link_to 'Back', admin_products_path, class:'button is-info' %>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="image-block">
<% @product.images.each do |image| %>
  <div class="image-box">
    <%= image_tag image.variant(resize: '500x300') if @product.images.attached? %>
    <%= link_to 'Remove', remove_image_admin_product_path(@product, image), method: :delete, class:'button is-small is-danger' %>
  </div>
  <% end %>
</div>

app/views/admin/products/edit.html.erb
<h1 class="title is-4">Edit product</h1>

<%= render 'form', product: @product %>

app/views/admin/products/index.html.erb
<h1 class="title">Product List</h1>

<%= link_to 'Add Product', new_admin_product_path, class:'button is-dark' %>

<section class="product-list columns is-multiline">
  <% @products.each do |product| %>
  <div class="column is-3">
    <div class="card">
      <div class="card-content">
        <h2 class="title is-5">Name: <%= link_to product.name, admin_product_path(product) %></h2>

        <p class="title is-6 is-uppercase">Status: <%= product.status %></p>
        <p>List Price: <%= product.list_price %></p>
        <p>Sell Price: <%= product.sell_price %></p>
        <p>SKU: <%= product.SKU %></p>
        <%= link_to 'Edit', edit_admin_product_path(product), class:'button is-small is-info' %>
        <%= link_to 'Delete', admin_product_path(product), method: :delete, class:'button is-small is-danger', data: {confirm: 'Sure to delete this product?'} %>
      </div>
    </div>
  </div>
  <% end  %>
</section>

app/views/admin/products/new.html.erb
<h1 class="title is-4">Add Product</h1>

<%= render 'form', product: @product %> 

app/views/admin/products/show.html.erb
<h1 class="title is-3"><%= @product.name %></h1>


<p class="is-size-5"> Description: <%= @product.description %></p>

<p>
  <strong>Images:</strong>
  <div>
    <% @product.images.each do |image| %>
      <%= image_tag image.variant(resize: '500x300') if @product.images.attached? %>
    <% end %>
  </div>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EC_Backend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <% if user_signed_in? %>
                <%= link_to current_user.email, edit_user_registration_path, class: 'button' %>
                <%= link_to "Logout", destroy_user_session_path, method: 'delete', class: 'button is-light' %>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path, class: 'button is-primary' %>
                <%= link_to "Sign in", new_user_session_path, class: 'button is-light' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div class="section">
      <div class="container">
        <%= notice %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/frontend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="section">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<% if product.errors.any? %>
<ul>
  <% product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<div>
<%= form_for product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :status %>
  <%= f.select :status, Product.statuses.keys %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :list_price %>
  <%= f.number_field :list_price %>

  <%= f.label :sell_price %>
  <%= f.number_field :sell_price %>

  <%= f.label :SKU %>
  <%= f.number_field :SKU %>

  <%= f.submit %>
<% end %>
</div>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1 class="title">Product</h1>

<section class="columns is-multiline">
  <% @products.each do |product| %>
  <div class="column is-3">
    <div class="card">
      <div class="card-image">
        <figure class="image is-3by4">
          <% if product.images.attached? %>
          <% image = product.images.first %>
          <%= image_tag image.variant(resize_to_limit: [300, 250]) %>
          <% else %>
          <img src="https://fakeimg.pl/150x100/?retina=1&text=こんにちは&font=noto">
          <% end %>
        </figure>
      </div>
      <header class="card-header">
        <h2 class="card-header-title is-centered"><%= link_to product.name, product_path(product) %></h2>
      </header>
      <div class="card-content">
        <p>
          <div>
            <strong>List Price: </strong>
            <%= product.list_price %>
          </div>
        </p>
        <p>
          <div>
            <strong>Sell Price: </strong>
            <%= product.sell_price %>
          </div>
        </p>
      </div>
    </div>
  </div>
  <% end  %>
</section>

app/views/products/show.html.erb
<h1 class="title is-3"> <%= @product.name %></h1>
<p>
  <div>
    <strong>Description: </strong>
    <%= @product.description %>
  </div>
</p>
<p>
  <div>
    <strong>Sell price: </strong>
    <%= @product.sell_price %>
  </div>
</p>
<p>
  <div>
    <strong>SKU: </strong>
    <%= @product.SKU %>
  </div>
</p>

<div>
<% @product.images.each do |image| %>
  <%= image_tag image.variant(resize_to_limit: [500, 300]) %>
<% end %>
</div>